package cn.weChat.model.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.Table;

@ToString
@Getter
@Setter
public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.tname
     *
     * @mbggenerated Thu Sep 19 18:23:57 CST 2019
     */
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.tname
     *
     * @return the value of test.tname
     *
     * @mbggenerated Thu Sep 19 18:23:57 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.tname
     *
     * @param tname the value for test.tname
     *
     * @mbggenerated Thu Sep 19 18:23:57 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname;
    }
}