package cn.weChat.model.entity;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("pwd is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("pwd is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("pwd =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("pwd <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("pwd >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("pwd >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("pwd <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("pwd <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("pwd like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("pwd not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("pwd in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("pwd not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("pwd between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("pwd not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andDesignValueIsNull() {
            addCriterion("design_value is null");
            return (Criteria) this;
        }

        public Criteria andDesignValueIsNotNull() {
            addCriterion("design_value is not null");
            return (Criteria) this;
        }

        public Criteria andDesignValueEqualTo(String value) {
            addCriterion("design_value =", value, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueNotEqualTo(String value) {
            addCriterion("design_value <>", value, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueGreaterThan(String value) {
            addCriterion("design_value >", value, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueGreaterThanOrEqualTo(String value) {
            addCriterion("design_value >=", value, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueLessThan(String value) {
            addCriterion("design_value <", value, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueLessThanOrEqualTo(String value) {
            addCriterion("design_value <=", value, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueLike(String value) {
            addCriterion("design_value like", value, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueNotLike(String value) {
            addCriterion("design_value not like", value, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueIn(List<String> values) {
            addCriterion("design_value in", values, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueNotIn(List<String> values) {
            addCriterion("design_value not in", values, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueBetween(String value1, String value2) {
            addCriterion("design_value between", value1, value2, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignValueNotBetween(String value1, String value2) {
            addCriterion("design_value not between", value1, value2, "designValue");
            return (Criteria) this;
        }

        public Criteria andDesignInfoIsNull() {
            addCriterion("design_info is null");
            return (Criteria) this;
        }

        public Criteria andDesignInfoIsNotNull() {
            addCriterion("design_info is not null");
            return (Criteria) this;
        }

        public Criteria andDesignInfoEqualTo(String value) {
            addCriterion("design_info =", value, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoNotEqualTo(String value) {
            addCriterion("design_info <>", value, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoGreaterThan(String value) {
            addCriterion("design_info >", value, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoGreaterThanOrEqualTo(String value) {
            addCriterion("design_info >=", value, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoLessThan(String value) {
            addCriterion("design_info <", value, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoLessThanOrEqualTo(String value) {
            addCriterion("design_info <=", value, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoLike(String value) {
            addCriterion("design_info like", value, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoNotLike(String value) {
            addCriterion("design_info not like", value, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoIn(List<String> values) {
            addCriterion("design_info in", values, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoNotIn(List<String> values) {
            addCriterion("design_info not in", values, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoBetween(String value1, String value2) {
            addCriterion("design_info between", value1, value2, "designInfo");
            return (Criteria) this;
        }

        public Criteria andDesignInfoNotBetween(String value1, String value2) {
            addCriterion("design_info not between", value1, value2, "designInfo");
            return (Criteria) this;
        }

        public Criteria andInfoIsNull() {
            addCriterion("info is null");
            return (Criteria) this;
        }

        public Criteria andInfoIsNotNull() {
            addCriterion("info is not null");
            return (Criteria) this;
        }

        public Criteria andInfoEqualTo(String value) {
            addCriterion("info =", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotEqualTo(String value) {
            addCriterion("info <>", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThan(String value) {
            addCriterion("info >", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThanOrEqualTo(String value) {
            addCriterion("info >=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThan(String value) {
            addCriterion("info <", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThanOrEqualTo(String value) {
            addCriterion("info <=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLike(String value) {
            addCriterion("info like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotLike(String value) {
            addCriterion("info not like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoIn(List<String> values) {
            addCriterion("info in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotIn(List<String> values) {
            addCriterion("info not in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoBetween(String value1, String value2) {
            addCriterion("info between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotBetween(String value1, String value2) {
            addCriterion("info not between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentTypeIsNull() {
            addCriterion("student_type is null");
            return (Criteria) this;
        }

        public Criteria andStudentTypeIsNotNull() {
            addCriterion("student_type is not null");
            return (Criteria) this;
        }

        public Criteria andStudentTypeEqualTo(String value) {
            addCriterion("student_type =", value, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeNotEqualTo(String value) {
            addCriterion("student_type <>", value, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeGreaterThan(String value) {
            addCriterion("student_type >", value, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("student_type >=", value, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeLessThan(String value) {
            addCriterion("student_type <", value, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeLessThanOrEqualTo(String value) {
            addCriterion("student_type <=", value, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeLike(String value) {
            addCriterion("student_type like", value, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeNotLike(String value) {
            addCriterion("student_type not like", value, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeIn(List<String> values) {
            addCriterion("student_type in", values, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeNotIn(List<String> values) {
            addCriterion("student_type not in", values, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeBetween(String value1, String value2) {
            addCriterion("student_type between", value1, value2, "studentType");
            return (Criteria) this;
        }

        public Criteria andStudentTypeNotBetween(String value1, String value2) {
            addCriterion("student_type not between", value1, value2, "studentType");
            return (Criteria) this;
        }

        public Criteria andUpathIsNull() {
            addCriterion("upath is null");
            return (Criteria) this;
        }

        public Criteria andUpathIsNotNull() {
            addCriterion("upath is not null");
            return (Criteria) this;
        }

        public Criteria andUpathEqualTo(String value) {
            addCriterion("upath =", value, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathNotEqualTo(String value) {
            addCriterion("upath <>", value, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathGreaterThan(String value) {
            addCriterion("upath >", value, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathGreaterThanOrEqualTo(String value) {
            addCriterion("upath >=", value, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathLessThan(String value) {
            addCriterion("upath <", value, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathLessThanOrEqualTo(String value) {
            addCriterion("upath <=", value, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathLike(String value) {
            addCriterion("upath like", value, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathNotLike(String value) {
            addCriterion("upath not like", value, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathIn(List<String> values) {
            addCriterion("upath in", values, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathNotIn(List<String> values) {
            addCriterion("upath not in", values, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathBetween(String value1, String value2) {
            addCriterion("upath between", value1, value2, "upath");
            return (Criteria) this;
        }

        public Criteria andUpathNotBetween(String value1, String value2) {
            addCriterion("upath not between", value1, value2, "upath");
            return (Criteria) this;
        }

        public Criteria andBpathIsNull() {
            addCriterion("bpath is null");
            return (Criteria) this;
        }

        public Criteria andBpathIsNotNull() {
            addCriterion("bpath is not null");
            return (Criteria) this;
        }

        public Criteria andBpathEqualTo(String value) {
            addCriterion("bpath =", value, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathNotEqualTo(String value) {
            addCriterion("bpath <>", value, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathGreaterThan(String value) {
            addCriterion("bpath >", value, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathGreaterThanOrEqualTo(String value) {
            addCriterion("bpath >=", value, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathLessThan(String value) {
            addCriterion("bpath <", value, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathLessThanOrEqualTo(String value) {
            addCriterion("bpath <=", value, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathLike(String value) {
            addCriterion("bpath like", value, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathNotLike(String value) {
            addCriterion("bpath not like", value, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathIn(List<String> values) {
            addCriterion("bpath in", values, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathNotIn(List<String> values) {
            addCriterion("bpath not in", values, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathBetween(String value1, String value2) {
            addCriterion("bpath between", value1, value2, "bpath");
            return (Criteria) this;
        }

        public Criteria andBpathNotBetween(String value1, String value2) {
            addCriterion("bpath not between", value1, value2, "bpath");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andRoteIsNull() {
            addCriterion("rote is null");
            return (Criteria) this;
        }

        public Criteria andRoteIsNotNull() {
            addCriterion("rote is not null");
            return (Criteria) this;
        }

        public Criteria andRoteEqualTo(String value) {
            addCriterion("rote =", value, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteNotEqualTo(String value) {
            addCriterion("rote <>", value, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteGreaterThan(String value) {
            addCriterion("rote >", value, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteGreaterThanOrEqualTo(String value) {
            addCriterion("rote >=", value, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteLessThan(String value) {
            addCriterion("rote <", value, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteLessThanOrEqualTo(String value) {
            addCriterion("rote <=", value, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteLike(String value) {
            addCriterion("rote like", value, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteNotLike(String value) {
            addCriterion("rote not like", value, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteIn(List<String> values) {
            addCriterion("rote in", values, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteNotIn(List<String> values) {
            addCriterion("rote not in", values, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteBetween(String value1, String value2) {
            addCriterion("rote between", value1, value2, "rote");
            return (Criteria) this;
        }

        public Criteria andRoteNotBetween(String value1, String value2) {
            addCriterion("rote not between", value1, value2, "rote");
            return (Criteria) this;
        }

        public Criteria andDesignNianIsNull() {
            addCriterion("design_nian is null");
            return (Criteria) this;
        }

        public Criteria andDesignNianIsNotNull() {
            addCriterion("design_nian is not null");
            return (Criteria) this;
        }

        public Criteria andDesignNianEqualTo(Integer value) {
            addCriterion("design_nian =", value, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianNotEqualTo(Integer value) {
            addCriterion("design_nian <>", value, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianGreaterThan(Integer value) {
            addCriterion("design_nian >", value, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianGreaterThanOrEqualTo(Integer value) {
            addCriterion("design_nian >=", value, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianLessThan(Integer value) {
            addCriterion("design_nian <", value, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianLessThanOrEqualTo(Integer value) {
            addCriterion("design_nian <=", value, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianIn(List<Integer> values) {
            addCriterion("design_nian in", values, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianNotIn(List<Integer> values) {
            addCriterion("design_nian not in", values, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianBetween(Integer value1, Integer value2) {
            addCriterion("design_nian between", value1, value2, "designNian");
            return (Criteria) this;
        }

        public Criteria andDesignNianNotBetween(Integer value1, Integer value2) {
            addCriterion("design_nian not between", value1, value2, "designNian");
            return (Criteria) this;
        }

        public Criteria andIphoneIsNull() {
            addCriterion("iphone is null");
            return (Criteria) this;
        }

        public Criteria andIphoneIsNotNull() {
            addCriterion("iphone is not null");
            return (Criteria) this;
        }

        public Criteria andIphoneEqualTo(String value) {
            addCriterion("iphone =", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneNotEqualTo(String value) {
            addCriterion("iphone <>", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneGreaterThan(String value) {
            addCriterion("iphone >", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneGreaterThanOrEqualTo(String value) {
            addCriterion("iphone >=", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneLessThan(String value) {
            addCriterion("iphone <", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneLessThanOrEqualTo(String value) {
            addCriterion("iphone <=", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneLike(String value) {
            addCriterion("iphone like", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneNotLike(String value) {
            addCriterion("iphone not like", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneIn(List<String> values) {
            addCriterion("iphone in", values, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneNotIn(List<String> values) {
            addCriterion("iphone not in", values, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneBetween(String value1, String value2) {
            addCriterion("iphone between", value1, value2, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneNotBetween(String value1, String value2) {
            addCriterion("iphone not between", value1, value2, "iphone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 19 18:03:29 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Thu Sep 19 18:03:29 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}