package cn.weChat.model.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pwd
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.design_value
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String designValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.design_info
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String designInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.info
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.student_name
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.student_type
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String studentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upath
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String upath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bpath
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String bpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.type
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rote
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String rote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.design_nian
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private Integer designNian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iphone
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    private String iphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pwd
     *
     * @return the value of user.pwd
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pwd
     *
     * @param pwd the value for user.pwd
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.design_value
     *
     * @return the value of user.design_value
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getDesignValue() {
        return designValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.design_value
     *
     * @param designValue the value for user.design_value
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setDesignValue(String designValue) {
        this.designValue = designValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.design_info
     *
     * @return the value of user.design_info
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getDesignInfo() {
        return designInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.design_info
     *
     * @param designInfo the value for user.design_info
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setDesignInfo(String designInfo) {
        this.designInfo = designInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.info
     *
     * @return the value of user.info
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.info
     *
     * @param info the value for user.info
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.student_name
     *
     * @return the value of user.student_name
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.student_name
     *
     * @param studentName the value for user.student_name
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.student_type
     *
     * @return the value of user.student_type
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getStudentType() {
        return studentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.student_type
     *
     * @param studentType the value for user.student_type
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setStudentType(String studentType) {
        this.studentType = studentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upath
     *
     * @return the value of user.upath
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getUpath() {
        return upath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upath
     *
     * @param upath the value for user.upath
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setUpath(String upath) {
        this.upath = upath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bpath
     *
     * @return the value of user.bpath
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getBpath() {
        return bpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bpath
     *
     * @param bpath the value for user.bpath
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setBpath(String bpath) {
        this.bpath = bpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rote
     *
     * @return the value of user.rote
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getRote() {
        return rote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rote
     *
     * @param rote the value for user.rote
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setRote(String rote) {
        this.rote = rote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.design_nian
     *
     * @return the value of user.design_nian
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public Integer getDesignNian() {
        return designNian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.design_nian
     *
     * @param designNian the value for user.design_nian
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setDesignNian(Integer designNian) {
        this.designNian = designNian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iphone
     *
     * @return the value of user.iphone
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public String getIphone() {
        return iphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iphone
     *
     * @param iphone the value for user.iphone
     *
     * @mbggenerated Wed Sep 18 14:47:57 CST 2019
     */
    public void setIphone(String iphone) {
        this.iphone = iphone;
    }
}